# Generated by Django 4.0.4 on 2023-04-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CAMDAIS', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Maths_Anxiety_symptoms', models.BooleanField(default=True)),
                ('Past_Experience', models.BooleanField(default=True)),
                ('Learning_Habit', models.BooleanField(default=True)),
                ('IQ', models.BooleanField(default=True)),
                ('Arithmetic', models.BooleanField(default=True)),
                ('Geometry', models.BooleanField(default=True)),
                ('Algebra', models.BooleanField(default=True)),
                ('Numerical_skill', models.BooleanField(default=True)),
                ('Working_Memory', models.BooleanField(default=True)),
            ],
        ),
    ]
