# Generated by Django 4.0.4 on 2023-05-24 22:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CAMDAIS', '0008_institute_institutetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.IntegerField()),
                ('level', models.IntegerField()),
                ('Maths_Anxiety_symptoms', models.CharField(default=None, max_length=250, null=True)),
                ('Past_Experience', models.CharField(default=None, max_length=250, null=True)),
                ('Learning_Habit', models.CharField(default=None, max_length=250, null=True)),
                ('IQ', models.CharField(default=None, max_length=250, null=True)),
                ('Arithmetic', models.CharField(default=None, max_length=250, null=True)),
                ('Geometry', models.CharField(default=None, max_length=250, null=True)),
                ('Algebra', models.CharField(default=None, max_length=250, null=True)),
                ('Numerical_skill', models.CharField(default=None, max_length=250, null=True)),
                ('Working_Memory', models.CharField(default=None, max_length=250, null=True)),
                ('Diagnostic_Result', models.CharField(default=None, max_length=1000, null=True)),
                ('examinee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinee', to=settings.AUTH_USER_MODEL)),
                ('examiner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examiner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
